version: '3.7'
services:
  bot:
    build:
      context: ./bot
    restart: always
    environment:
      - PORT=8080
      - DOMAIN=trust.ctf.zoolab.org
      - REPORT_HOST=web
      - FLAG=FLAG{dummy_flag}
  web:
    build:
      context: ./web
    environment:
      - BOT_HOST=bot
      - BOT_PORT=8080
    restart: always
    ports:
      - 8080:80
